### ISSUE TITLE
Switch from jbundler to lock_jar

### ISSUE THREAD

**Issue by pangloss** [joekiller/jruby-kafka#13]
I switched all of my libraries over to [lock_jar](https://github.com/mguymon/lock_jar) the other day because it's the only JRuby maven integration that I know of that *just works*.

For an example of how I set it up in one project, see [this commit](https://github.com/pangloss/pacer-orient/commit/fad62a189a160eaa075b78293983b5de67ddd8a8).

If you're ok with the change, I'll make a pull request.

**Comment by joekiller** [comment]
Hi I decided to use https://github.com/mkristian/jar-dependencies as it is more in line with how the logstash/elasticsearch guys are integrating jars into their libraries, ie https://github.com/logstash-plugins/logstash-output-elasticsearch.  Thank you for your feedback and support.
