### ISSUE TITLE
gemspec jbundler version

### ISSUE THREAD

**Issue by colinsurprenant** [joekiller/jruby-kafka#15]
Is there a particular reason why the jbundler version is frozen a 0.5.5 in the gemspec? https://github.com/joekiller/jruby-kafka/blob/master/jruby-kafka.gemspec#L21

I'd suggest either not specifying version or putting ">= 0.5.5" so that upstream dependencies that also depends on a more recent version of jbundler does not end in a version conflict.

**Comment by joekiller** [comment]
This should be fixed with commit https://github.com/joekiller/jruby-kafka/commit/9e8e8b38fbf04cb37cc50d0fcc3c7cd57bc05b2e
