### ISSUE TITLE
Consumer starting where it left off instead at very beginning or very end of topic

### ISSUE THREAD

**Issue by graphex** [joekiller/jruby-kafka#16]
Because group.rb calls `Java::kafka::utils::ZkUtils.maybeDeletePath(@zk_connect, "/consumers/#{@group_id}")` every time it runs if `@auto_offset_reset == 'smallest'`, there is no way for a consumer to pick up where it is left off by setting either `reset_beginning` or `auto_offset_reset`. The desired behavior is auto_offset_reset = 'smallest' to let a consumer start at the most recent offset for the group+partition that is stored in Zookeeper, but the gem deletes the stored offsets for the entire group if `auto_offset_reset` is set to 'smallest'. Am I missing something?

I will make a PR with my suggested change, which allows `reset_beginning = 'from-beginning'` to clear out the group's offsets from all partitions, yet allows `auto_offset_reset = 'smallest'` to simply start at the most recently stored offset in ZK instead of at the end of the queue.

**Comment by joekiller** [comment]
Okay I've finally seen the light here. I'll accept the PR but am going to change it a bit to match how Kafka implemented fixing https://issues.apache.org/jira/browse/KAFKA-1431 https://github.com/apache/kafka/commit/b866c5506a936572c9a948c4bae68da0d045fc53

Will try to do this soon.

**Comment by joekiller** [comment]
Thanks for raising this @graphex it should be fixed now.

**Comment by graphex** [comment]
Glad to hear, will be putting it to the test soon! Thank you.

**Comment by agarwalpranaya** [comment]
Thanks Joe for the fix. I am facing the same issue. When is the next release planned with the latest fix?

**Comment by joekiller** [comment]
I pushed out 1.1.0.beta just now.

**Comment by agarwalpranaya** [comment]
Thanks a lot Joe. Is that release from the latest commit in master? https://github.com/joekiller/jruby-kafka/commits/master

**Comment by joekiller** [comment]
I pushed out 1.1.0 as non-beta this afternoon.  https://github.com/joekiller/jruby-kafka/releases/tag/v1.1.0 and https://rubygems.org/gems/jruby-kafka/versions/1.1.0-java
