### ISSUE TITLE
Where can I find group.rb?

### ISSUE THREAD

**Issue by keybod** [joekiller/jruby-kafka#34]
Hello~
I'm looking for group.rb file.
Actually, I'm messing around on logstash-input-kafka which is one of Logstash plugins.
The plugin uses 'Group' class. I wanted to see the source code but I couldn't find it in this repository.
Then, I came across a web site that was https://rubygems.org/gems/jruby-kafka/versions/0.1.0 and installed the gem and I found the 'Group' class in a file named 'group.rb'.

So I have a question for this, Is it deprecated class?

**Comment by joekiller** [comment]
Master has 2.0 code. Check out https://github.com/joekiller/jruby-kafka/tree/5ba0a2b6e2427901f7209341a0dcc3341cb36cc0 for the most recent release
