### ISSUE TITLE
Latest gem release (for jruby) doesn't have new, simpler consumer.

### ISSUE THREAD

**Issue by yarmiganosca** [joekiller/jruby-kafka#36]
Could you release a new gem version to rubygems with the simpler consumer code?

**Comment by joekiller** [comment]
Yeah it'll be a 2.0. Sorry for the delay. Thanks for the reminder.

**Comment by joekiller** [comment]
The latest and greatest jruby-kafka v2.0 is on ruby-gems! Hurrah!!!  Big thanks to @eliaslevy and @ashangit for their contributions!

v1.5.0 is a non-breaking release that supports Kafka 0.8.2.2 and v2.0 includes the simpler consumer.
