### ISSUE TITLE
Are there any plans to upgrade to the latest Kafka API? I would like mutual TLS support

### ISSUE THREAD

**Issue by andreicristianpetcu** [joekiller/jruby-kafka#40]
Hello,

Are there any plans to upgrade to the latest Kafka API? I would like to use mutual TLS support with the Logstash-Kafka plugin and this requires the latest v0.9 Kafka.

Thank you

**Comment by joekiller** [comment]
I'd love a PR but if not when I get time I'm going to explore @suyograo's logstash-input-kafka implementation and merge it into here as a 3.0. 
https://github.com/logstash-plugins/logstash-input-kafka/tree/update/0.9 
https://github.com/logstash-plugins/logstash-input-kafka/issues/48

**Comment by andreicristianpetcu** [comment]
Thank you for your quick reply! I will follow this issue and the one from logstash-input-kafka

**Comment by joekiller** [comment]
Check out jruby-kafka v3.2.

**Comment by andreicristianpetcu** [comment]
Thank you, @joekiller! I will test it soon!

**Comment by pencal** [comment]
@joekiller  sorry for stating the obvious, where can I find out the configurations of the jruby-kafka v3.2? In the Kafka documentation, we have the . convention such as consumer.id, whereas in the plugin, I see the _ convention such as consumer_id. Is it just a matter following the config in Kafka documentation and switch all the . to _?

**Comment by joekiller** [comment]
Correct Calvin. Underscores are more rubyesc. Just use the . settings and
use underscores.

-Joe
Sent via mobile.
