### ISSUE TITLE
Namespace conflicts

### ISSUE THREAD

**Issue by guyisra** [joekiller/jruby-kafka#49]
Hey,

A lot of kafka related gems use the namespace `Kafka`

Would it be possible to rename the namespace of this gem to something else so it will be more unique (like `JKafka` or something)

thanks

**Comment by joekiller** [comment]
What conflict are you.experiencing? I'm somewhat less inclined to indulge this as this project has been going since 2013 and is the only JRuby Kafka platform that I know of.

**Comment by guyisra** [comment]
Kafka::Consumer is also used in https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb 

While I understand and think that the later gem should rename the namespace (I also requested it there) I opened it here to try and solve this at either end :)

**Comment by joekiller** [comment]
Yeah I just found their project. It's a native Ruby implementation so while
there is some potential for conflict I'd expect each gem to have different
target audiences.

Trying something out? Getting on the Kafka train? Send me an email if you
have questions.
