### ISSUE TITLE
log4j warnings

### ISSUE THREAD

**Issue by ghost** [joekiller/jruby-kafka#56]
Hi,

I'm using the 2.2.2 gem (not self built) with jruby 9.1.5.0. I'm not familiar at all with Java, so I'm not sure how to deal with these errors:

log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

I clicked the link the the error, but it assumes the reader is proficient with Java. Is there something I can do to make the error go away and/or make the library use the built-in Ruby logger?

Thanks for supporting Kafka 0.8! I'm using only the consumer and my code is nearly identical to your consumer example.

I have a few other issues with the library, should I open additional issues or discuss them here?

**Comment by joekiller** [comment]
Yes you can open issues. You need a log4j.properties file on the classpath.
https://github.com/joekiller/jruby-kafka/blob/master/log4j.properties is an
example. You'd likely want to turn it up the logging level a little by
setting it to INFO instead of the current FATAL

-Joe
Sent via mobile.

**Comment by ghost** [comment]
Problem solved! I assumed "on the classpath" meant at the top level of my app and it worked.

I was having a problem installing with bundler the other day, but that appears to have self-corrected, so my only other issue might be discovered in the logging that I now have. If not, I'll open a new case. Thanks for the fix!
